/**
 * E-invoice (IRN + signed QR) and e-way bill through the GSP (Module 2, Phase 2).
 *
 * E-invoice: only when the gst_rules "einvoice" switch is on for the invoice
 * date, the shop has declared it is above the turnover threshold
 * (shops.einvoice_applicable — GoKesari cannot see the shop's whole
 * turnover), and the invoice is B2B (buyer GSTIN). Queued in the delivery's
 * transaction, requested just after commit; one record per invoice and a
 * fixed request id, so a retry never makes a second IRN (a DUPLICATE answer
 * fetches the existing one). Failed requests are retried by the safety-net
 * sweep while the reporting window allows, and can be retried by hand.
 *
 * E-way bill: needs the distance and vehicle, which GoKesari's local
 * deliveries do not record, so it is generated by hand from the order when
 * the value rules (gst_rules "ewayBill") say one is needed.
 */
import { and, eq, inArray, lt } from "drizzle-orm";

import { conflict, notFound, validationFailed } from "@/lib/errors";
import { gstState } from "@/lib/gst-states";
import { db, type DbClient } from "@/server/db";
import { einvoiceRecords, ewayBills, shops, taxInvoices, type EinvoiceRecord, type TaxInvoice } from "@/server/db/schema";
import { invoiceToCanonical } from "@/server/integrations/documents";
import { AUDIT_ACTIONS, recordAudit } from "@/server/services/audit";
import type { InvoiceSnapshot } from "@/server/services/invoices";
import { getGspProvider, GspError } from "./gsp";
import { getGstRule } from "./rules";

interface EinvoiceRule {
  enabled: boolean;
  turnoverThresholdPaise: number;
  b2bOnly: boolean;
}

interface EwayRule {
  enabled: boolean;
  interStateThresholdPaise: number;
  intraStateThresholdPaise: Record<string, number>;
}

export async function einvoiceApplies(invoice: TaxInvoice, client: DbClient = db): Promise<{ applies: boolean; reason: string }> {
  const rule = await getGstRule<EinvoiceRule>("einvoice", invoice.issuedAt, client);
  if (!rule?.enabled) return { applies: false, reason: "E-invoicing is switched off in GST settings." };
  const s = invoice.snapshot as unknown as InvoiceSnapshot;
  if (s.kind !== "TAX_INVOICE" || !s.seller.gstin) return { applies: false, reason: "Not a tax invoice of a GST-registered shop." };
  if (rule.b2bOnly !== false && !s.buyer.gstin) return { applies: false, reason: "Not a B2B invoice (no buyer GSTIN)." };
  const [shop] = await client.select({ applicable: shops.einvoiceApplicable }).from(shops).where(eq(shops.id, invoice.shopId));
  if (!shop?.applicable) return { applies: false, reason: "The shop has not declared that e-invoicing applies to it." };
  return { applies: true, reason: "" };
}

/** Called in the delivery's transaction after the invoice is issued. */
export async function queueEinvoice(invoice: TaxInvoice, client: DbClient = db): Promise<string | null> {
  const { applies } = await einvoiceApplies(invoice, client);
  if (!applies) return null;
  const [row] = await client
    .insert(einvoiceRecords)
    .values({ taxInvoiceId: invoice.id, shopId: invoice.shopId, gsp: providerName(), requestId: `irn:${invoice.id}`, status: "PENDING" })
    .onConflictDoNothing()
    .returning({ id: einvoiceRecords.id });
  if (!row) return null;
  if (process.env.INTEGRATION_AUTODISPATCH !== "off") {
    setTimeout(() => void processEinvoice(row.id).catch((e) => console.error("[gst] e-invoice failed", e)), client === db ? 0 : 2_000).unref?.();
  }
  return row.id;
}

function providerName(): string {
  try {
    return getGspProvider().name;
  } catch {
    return "unconfigured";
  }
}

/** Requests the IRN for a PENDING / FAILED record. Safe to call twice (row lock, idempotent request). */
export async function processEinvoice(recordId: string): Promise<EinvoiceRecord | null> {
  return db.transaction(async (tx) => {
    const [record] = await tx
      .select()
      .from(einvoiceRecords)
      .where(and(eq(einvoiceRecords.id, recordId), inArray(einvoiceRecords.status, ["PENDING", "FAILED"])))
      .for("update", { skipLocked: true });
    if (!record) return null;
    const [invoice] = await tx.select().from(taxInvoices).where(eq(taxInvoices.id, record.taxInvoiceId));
    const doc = invoiceToCanonical(invoice, new Map());
    const now = new Date();
    try {
      const gsp = getGspProvider();
      let result;
      try {
        result = await gsp.generateIrn({ requestId: record.requestId, invoice: doc });
      } catch (error) {
        if (!(error instanceof GspError && error.code === "DUPLICATE")) throw error;
        result = await gsp.irnByDocument(doc.seller.gstin!, "INV", doc.number, doc.date);
        if (!result) throw error;
      }
      const [done] = await tx
        .update(einvoiceRecords)
        .set({
          status: "GENERATED",
          gsp: gsp.name,
          irn: result.irn,
          ackNo: result.ackNo,
          ackDate: new Date(result.ackDate),
          signedInvoice: result.signedInvoice,
          signedQr: result.signedQr,
          errorCode: null,
          errorMessage: null,
          updatedAt: now,
        })
        .where(eq(einvoiceRecords.id, record.id))
        .returning();
      await recordAudit(
        { action: AUDIT_ACTIONS.EINVOICE_GENERATED, entityType: "tax_invoice", entityId: invoice.id, newValue: { invoiceNumber: invoice.invoiceNumber, irn: result.irn, ackNo: result.ackNo, gsp: gsp.name } },
        tx,
      );
      return done;
    } catch (error) {
      const e = error instanceof GspError ? error : new GspError("UNAVAILABLE", error instanceof Error ? error.message : String(error));
      const [failed] = await tx
        .update(einvoiceRecords)
        .set({ status: "FAILED", errorCode: e.code, errorMessage: e.detail ? `${e.message} (${e.detail})` : e.message, updatedAt: now })
        .where(eq(einvoiceRecords.id, record.id))
        .returning();
      return failed;
    }
  });
}

/** Manual "generate / retry e-invoice" for an invoice. */
export async function requestEinvoice(invoiceId: string): Promise<EinvoiceRecord> {
  const [invoice] = await db.select().from(taxInvoices).where(eq(taxInvoices.id, invoiceId));
  if (!invoice) throw notFound("Invoice");
  let [record] = await db.select().from(einvoiceRecords).where(eq(einvoiceRecords.taxInvoiceId, invoiceId));
  if (record?.status === "GENERATED") return record;
  if (record?.status === "CANCELLED") throw conflict("The e-invoice of this invoice was cancelled.");
  if (!record) {
    const { applies, reason } = await einvoiceApplies(invoice);
    if (!applies) throw validationFailed(reason);
    [record] = await db
      .insert(einvoiceRecords)
      .values({ taxInvoiceId: invoice.id, shopId: invoice.shopId, gsp: providerName(), requestId: `irn:${invoice.id}`, status: "PENDING" })
      .onConflictDoNothing()
      .returning();
    record ??= (await db.select().from(einvoiceRecords).where(eq(einvoiceRecords.taxInvoiceId, invoiceId)))[0];
  }
  const done = await processEinvoice(record.id);
  return done ?? record;
}

/** Safety net: FAILED requests that may succeed on retry (GSP down), within the reporting window. */
export async function retryFailedEinvoices(limit = 20): Promise<number> {
  const window = await getGstRule<{ days: number }>("einvoiceReportingWindow");
  const since = new Date(Date.now() - (window?.days ?? 30) * 86_400_000);
  const due = await db
    .select({ id: einvoiceRecords.id })
    .from(einvoiceRecords)
    .where(
      and(
        inArray(einvoiceRecords.status, ["PENDING", "FAILED"]),
        inArray(einvoiceRecords.errorCode, ["UNAVAILABLE", "NOT_CONFIGURED"]),
        lt(einvoiceRecords.updatedAt, new Date(Date.now() - 10 * 60_000)),
      ),
    )
    .limit(limit);
  let n = 0;
  for (const r of due) {
    const [rec] = await db.select({ createdAt: einvoiceRecords.createdAt }).from(einvoiceRecords).where(eq(einvoiceRecords.id, r.id));
    if (rec.createdAt < since) continue;
    if ((await processEinvoice(r.id))?.status === "GENERATED") n += 1;
  }
  // PENDING records never attempted (server restarted before the post-commit call).
  const stuck = await db
    .select({ id: einvoiceRecords.id })
    .from(einvoiceRecords)
    .where(and(eq(einvoiceRecords.status, "PENDING"), lt(einvoiceRecords.createdAt, new Date(Date.now() - 5 * 60_000))))
    .limit(limit);
  for (const r of stuck) if ((await processEinvoice(r.id))?.status === "GENERATED") n += 1;
  return n;
}

/* ------------------------------------------------------------ e-way bill */

export async function ewayBillRequirement(invoice: TaxInvoice): Promise<{ required: boolean; reason: string; thresholdPaise: number | null }> {
  const rule = await getGstRule<EwayRule>("ewayBill", invoice.issuedAt);
  if (!rule?.enabled) return { required: false, reason: "E-way bills are switched off in GST settings.", thresholdPaise: null };
  const s = invoice.snapshot as unknown as InvoiceSnapshot;
  const alpha = gstState(s.seller.gstin ?? s.seller.stateCode)?.alpha ?? "DEFAULT";
  const threshold = s.supplyType === "INTER" ? rule.interStateThresholdPaise : (rule.intraStateThresholdPaise[alpha] ?? rule.intraStateThresholdPaise.DEFAULT);
  if (threshold == null) return { required: false, reason: "No threshold set for this state.", thresholdPaise: null };
  return invoice.totalPaise > threshold
    ? { required: true, reason: "The consignment value is above the e-way bill limit.", thresholdPaise: threshold }
    : { required: false, reason: "Below the e-way bill limit.", thresholdPaise: threshold };
}

export async function generateEwayBill(
  invoiceId: string,
  input: { distanceKm: number; vehicleNo?: string | null },
  actor: { id: string; role?: string },
) {
  const [invoice] = await db.select().from(taxInvoices).where(eq(taxInvoices.id, invoiceId));
  if (!invoice) throw notFound("Invoice");
  const rule = await getGstRule<EwayRule>("ewayBill", invoice.issuedAt);
  if (!rule?.enabled) throw validationFailed("E-way bills are switched off in GST settings.");
  const [existing] = await db.select().from(ewayBills).where(eq(ewayBills.taxInvoiceId, invoiceId));
  if (existing?.status === "GENERATED") throw conflict(`E-way bill ${existing.ewbNo} already exists for this invoice.`);
  const vehicleNo = input.vehicleNo?.replace(/\s+/g, "").toUpperCase() || null;
  if (vehicleNo && !/^[A-Z]{2}\d{1,2}[A-Z]{0,3}\d{4}$/.test(vehicleNo)) throw validationFailed("Vehicle number looks wrong (e.g. MH12AB1234).");
  const [einv] = await db.select({ irn: einvoiceRecords.irn }).from(einvoiceRecords).where(and(eq(einvoiceRecords.taxInvoiceId, invoiceId), eq(einvoiceRecords.status, "GENERATED")));
  const gsp = getGspProvider();
  const now = new Date();
  try {
    const result = await gsp.generateEwayBill({
      requestId: `ewb:${invoiceId}`,
      invoice: invoiceToCanonical(invoice, new Map()),
      distanceKm: input.distanceKm,
      vehicleNo,
      irn: einv?.irn ?? null,
    });
    const values = {
      taxInvoiceId: invoiceId,
      shopId: invoice.shopId,
      gsp: gsp.name,
      status: "GENERATED" as const,
      ewbNo: result.ewbNo,
      validUpto: new Date(result.validUpto),
      distanceKm: Math.round(input.distanceKm),
      vehicleNo,
      errorMessage: null,
      updatedAt: now,
    };
    const [row] = await db.insert(ewayBills).values(values).onConflictDoUpdate({ target: ewayBills.taxInvoiceId, set: values }).returning();
    await recordAudit({ actorId: actor.id, action: AUDIT_ACTIONS.EWAY_BILL_GENERATED, entityType: "tax_invoice", entityId: invoiceId, newValue: { ewbNo: row.ewbNo, distanceKm: row.distanceKm, vehicleNo } });
    return row;
  } catch (error) {
    if (!(error instanceof GspError)) throw error;
    const values = { taxInvoiceId: invoiceId, shopId: invoice.shopId, gsp: gsp.name, status: "FAILED" as const, errorMessage: error.message, distanceKm: Math.round(input.distanceKm), vehicleNo, updatedAt: now };
    await db.insert(ewayBills).values(values).onConflictDoUpdate({ target: ewayBills.taxInvoiceId, set: values });
    throw validationFailed(`The e-way bill was not generated: ${error.message}`);
  }
}

export async function gstDocumentsFor(invoiceId: string) {
  const [einvoice] = await db.select().from(einvoiceRecords).where(eq(einvoiceRecords.taxInvoiceId, invoiceId));
  const [eway] = await db.select().from(ewayBills).where(eq(ewayBills.taxInvoiceId, invoiceId));
  return {
    einvoice: einvoice
      ? { status: einvoice.status, irn: einvoice.irn, ackNo: einvoice.ackNo, ackDate: einvoice.ackDate, error: einvoice.errorMessage }
      : null,
    ewayBill: eway ? { status: eway.status, ewbNo: eway.ewbNo, validUpto: eway.validUpto, error: eway.errorMessage } : null,
  };
}
