/**
 * Open*Facts category tags -> Gokesari standard categories.
 *
 * Built from the tags that actually occur in the India pilot samples (Open Food
 * Facts, Open Beauty Facts, Open Products Facts, Open Pet Food Facts). Tags too
 * generic to place a product ("en:non-food-products", "en:cosmetic-products",
 * "en:plant-based-foods") are intentionally left unmapped: an unmapped product is
 * filed as Uncategorised and shows up on the data-quality dashboard, which is
 * better than a confident wrong category.
 *
 * When several tags of one product map, the deepest standard category wins.
 */
import type { CategoryRules } from "../../taxonomy/mapper";

const G = "grocery/staples";
const F = "food";

export const OPEN_FACTS_RULES: CategoryRules = {
  tags: {
    /* ------------------------------------------------------------ grocery */
    "en:rices": `${G}/rice`,
    "en:aromatic-rices": `${G}/rice`,
    "en:indica-rices": `${G}/rice`,
    "en:long-grain-rices": `${G}/rice`,
    "en:basmati-rices": `${G}/rice/basmati-rice`,
    "en:pulses": `${G}/pulses-and-lentils`,
    "en:legumes": `${G}/pulses-and-lentils`,
    "en:legume-seeds": `${G}/pulses-and-lentils`,
    "en:legumes-and-their-products": `${G}/pulses-and-lentils`,
    "en:common-beans": `${G}/pulses-and-lentils/rajma-and-beans`,
    "en:cereal-grains": `${G}/flours-and-grains`,
    "en:cereals-and-their-products": `${G}/flours-and-grains`,
    "en:flours": `${G}/flours-and-grains`,
    "en:spices": `${G}/spices-and-masalas`,
    "en:herbs-and-spices": `${G}/spices-and-masalas`,
    "en:herbs": `${G}/spices-and-masalas`,
    "en:vegetable-oils": `${G}/edible-oils`,
    "en:vegetable-fats": `${G}/edible-oils`,
    "en:olive-oils": `${G}/edible-oils/olive-oil`,
    "en:sugars": `${G}/sugar-jaggery-and-salt/sugar`,
    "en:sweeteners": `${G}/sugar-jaggery-and-salt`,
    "en:salts": `${G}/sugar-jaggery-and-salt/salt`,
    "en:nuts": `${G}/dry-fruits-and-nuts`,
    "en:nuts-and-their-products": `${G}/dry-fruits-and-nuts`,
    "en:dried-fruits": `${G}/dry-fruits-and-nuts`,
    "en:dates": `${G}/dry-fruits-and-nuts/dates`,
    "en:cashew-nuts": `${G}/dry-fruits-and-nuts/cashews`,
    "en:almonds": `${G}/dry-fruits-and-nuts/almonds`,
    "en:pistachios": `${G}/dry-fruits-and-nuts/walnuts-and-others`,
    "en:fruits": "grocery/fresh-produce/fruits",
    "en:fresh-fruits": "grocery/fresh-produce/fruits",
    "en:tropical-fruits": "grocery/fresh-produce/fruits",
    "en:bananas": "grocery/fresh-produce/fruits",
    "en:mangoes": "grocery/fresh-produce/fruits",
    "en:vegetables": "grocery/fresh-produce/vegetables",
    "en:fresh-vegetables": "grocery/fresh-produce/vegetables",
    "en:leaf-vegetables": "grocery/fresh-produce/herbs-and-leafy-greens",
    "en:cabbages": "grocery/fresh-produce/vegetables",
    "en:green-peas": "grocery/fresh-produce/vegetables",

    /* --------------------------------------------------------------- food */
    "en:snacks": `${F}/snacks`,
    "en:salty-snacks": `${F}/snacks`,
    "en:appetizers": `${F}/snacks`,
    "en:crisps": `${F}/snacks/chips-and-crisps`,
    "en:chips-and-fries": `${F}/snacks/chips-and-crisps`,
    "en:biscuits": `${F}/biscuits-and-cookies`,
    "en:biscuits-and-crackers": `${F}/biscuits-and-cookies`,
    "en:biscuits-and-cakes": `${F}/biscuits-and-cookies`,
    "en:cookies": `${F}/biscuits-and-cookies/cookies`,
    "en:chocolates": `${F}/confectionery/chocolates`,
    "en:cocoa-and-its-products": `${F}/confectionery/chocolates`,
    "en:candies": `${F}/confectionery/candies-and-toffees`,
    "en:confectioneries": `${F}/confectionery`,
    "en:breakfast-cereals": `${F}/breakfast-and-cereals`,
    "en:cereal-flakes": `${F}/breakfast-and-cereals/cornflakes-and-muesli`,
    "en:extruded-cereals": `${F}/breakfast-and-cereals/cornflakes-and-muesli`,
    "en:breakfasts": `${F}/breakfast-and-cereals`,
    "en:condiments": `${F}/sauces-spreads-and-condiments`,
    "en:sauces": `${F}/sauces-spreads-and-condiments/ketchup-and-sauces`,
    "en:tomato-sauces": `${F}/sauces-spreads-and-condiments/ketchup-and-sauces`,
    "en:ketchup": `${F}/sauces-spreads-and-condiments/ketchup-and-sauces`,
    "en:vinegars": `${F}/sauces-spreads-and-condiments/vinegar`,
    "en:spreads": `${F}/sauces-spreads-and-condiments/jams-and-spreads`,
    "en:sweet-spreads": `${F}/sauces-spreads-and-condiments/jams-and-spreads`,
    "en:peanut-butters": `${F}/sauces-spreads-and-condiments/peanut-butter`,
    "en:pickles": `${F}/sauces-spreads-and-condiments/pickles-and-chutneys`,
    "en:breads": `${F}/bakery/bread`,
    "en:noodles": `${F}/instant-and-ready-to-eat/noodles`,
    "en:pastas": `${F}/instant-and-ready-to-eat/pasta-and-macaroni`,
    "en:soups": `${F}/instant-and-ready-to-eat/soups`,
    "en:frozen-foods": `${F}/frozen-foods`,
    "en:eggs": `${F}/eggs-meat-and-seafood/eggs`,
    "en:chicken-eggs": `${F}/eggs-meat-and-seafood/eggs`,

    /* ---------------------------------------------------------- beverages */
    "en:beverages": "beverages",
    "en:beverages-and-beverages-preparations": "beverages",
    "en:beverage-preparations": "beverages",
    "en:hot-beverages": "beverages",
    "en:plant-based-beverages": "beverages",
    "en:teas": "beverages/tea",
    "en:black-teas": "beverages/tea/black-tea",
    "en:green-teas": "beverages/tea/green-tea",
    "en:coffees": "beverages/coffee",
    "en:instant-coffees": "beverages/coffee/instant-coffee",
    "en:carbonated-drinks": "beverages/soft-drinks",
    "en:juices": "beverages/juices",
    "en:fruit-juices": "beverages/juices/fruit-juices",
    "en:waters": "beverages/water",
    "en:energy-drinks": "beverages/energy-and-health-drinks/energy-drinks",

    /* -------------------------------------------------------------- dairy */
    "en:dairies": "dairy",
    "en:milks": "dairy/milk",
    "en:milks-liquid-and-powder": "dairy/milk",
    "en:fermented-milk-products": "dairy/curd-and-yogurt",
    "en:yogurts": "dairy/curd-and-yogurt",
    "en:cheeses": "dairy/cheese",
    "en:butters": "dairy/butter-and-margarine",
    "en:creams": "dairy/cream-and-whipped-toppings",
    "en:ice-creams": "dairy/ice-cream-and-frozen-desserts",

    /* ------------------------------------------------------------- health */
    "en:dietary-supplements": "health-and-wellness/vitamins-and-supplements",
    "en:vitamins": "health-and-wellness/vitamins-and-supplements",
    "en:bodybuilding-supplements": "health-and-wellness/protein-and-nutrition",
    "en:protein-powders": "health-and-wellness/protein-and-nutrition",
    "en:protein-bars": "health-and-wellness/protein-and-nutrition",
    "en:medicine": "health-and-wellness",
    "en:medicines": "health-and-wellness",
    "en:medicine-drugs": "health-and-wellness",
    "en:medical-products": "health-and-wellness",
    "en:health-care": "health-and-wellness",

    /* ------------------------------------------------------ personal care */
    "en:personal-care": "personal-care",
    "en:hygiene": "personal-care",
    "en:shampoos": "personal-care/hair-care/shampoo",
    "en:shampoo": "personal-care/hair-care/shampoo",
    "en:hair-conditioners": "personal-care/hair-care/conditioner",
    "en:hair-oil": "personal-care/hair-care/hair-oil",
    "en:hair-oils": "personal-care/hair-care/hair-oil",
    "en:hair": "personal-care/hair-care",
    "en:hair-care": "personal-care/hair-care",
    "en:hair-serum": "personal-care/hair-care",
    "en:toothpastes": "personal-care/oral-care/toothpaste",
    "en:toothpaste": "personal-care/oral-care/toothpaste",
    "en:tooth-paste": "personal-care/oral-care/toothpaste",
    "fr:dentifrice": "personal-care/oral-care/toothpaste",
    "en:toothbrush": "personal-care/oral-care/toothbrushes",
    "en:toothbrushes": "personal-care/oral-care/toothbrushes",
    "en:soaps": "personal-care/bath-and-body/soaps",
    "en:soap": "personal-care/bath-and-body/soaps",
    "en:bar-soaps": "personal-care/bath-and-body/soaps",
    "en:body-wash": "personal-care/bath-and-body/body-wash",
    "en:body-gels": "personal-care/bath-and-body/body-wash",
    "en:showers-and-baths": "personal-care/bath-and-body",
    "en:body-lotion": "personal-care/bath-and-body/body-lotions",
    "en:body-milks": "personal-care/bath-and-body/body-lotions",
    "en:body-powders": "personal-care/bath-and-body/talcum-powder",
    "en:handwash": "personal-care/hand-wash-and-sanitisers",
    "en:hand-wash": "personal-care/hand-wash-and-sanitisers",
    "en:deodorants": "personal-care/deodorants",
    "en:deodorant": "personal-care/deodorants",
    "en:roll-on-deodorants": "personal-care/deodorants",
    "en:shaving": "personal-care/mens-grooming/shaving",
    "en:shaving-foam": "personal-care/mens-grooming/shaving",
    "en:condoms": "personal-care",
    "en:condom": "personal-care",
    "en:male-condoms": "personal-care",
    "en:baby-toddler": "personal-care/baby-care",
    "en:diapering": "personal-care/baby-care/diapers",
    "en:diapers": "personal-care/baby-care/diapers",

    /* ------------------------------------------------------------- beauty */
    "en:perfumes": "beauty/fragrances/perfumes",
    "en:women-perfumes": "beauty/fragrances/perfumes",
    "en:men-perfumes": "beauty/fragrances/perfumes",
    "en:moisturizer": "beauty/skincare/moisturisers-and-creams",
    "en:face-lotions": "beauty/skincare/moisturisers-and-creams",
    "en:face-wash": "beauty/skincare/face-wash-and-cleansers",
    "en:facewash": "beauty/skincare/face-wash-and-cleansers",
    "en:cleansers": "beauty/skincare/face-wash-and-cleansers",
    "en:face-scrubs": "beauty/skincare/face-wash-and-cleansers",
    "en:sunscreen": "beauty/skincare/sunscreen",
    "en:suncare": "beauty/skincare/sunscreen",
    "en:in-sun-protections": "beauty/skincare/sunscreen",
    "en:skincare": "beauty/skincare",
    "en:skin-care": "beauty/skincare",
    "en:face": "beauty/skincare",
    "en:makeup": "beauty/makeup",
    "en:nail-makeup": "beauty/makeup/nail-care",
    "en:nail-polish": "beauty/makeup/nail-care",

    /* ---------------------------------------------------- electronics etc. */
    "en:electronics": "electronics",
    "en:mobile-phones": "electronics/mobiles/smartphones",
    "en:smartphones": "electronics/mobiles/smartphones",
    "en:android-smartphones": "electronics/mobiles/smartphones/android-phones",
    "en:usb-cables": "electronics/power-and-accessories/cables",
    "en:electronics-accessories": "electronics/power-and-accessories",
    "en:headphones": "electronics/tvs-and-audio/headphones-and-earphones",
    "en:headphones-headsets": "electronics/tvs-and-audio/headphones-and-earphones",
    "en:audio": "electronics/tvs-and-audio",
    "en:computer-components": "electronics/computers/components",
    "en:input-devices": "electronics/computers/peripherals",

    /* ------------------------------------------------------ home, stationery */
    "en:household-chemicals": "home-and-kitchen/cleaning-and-household",
    "en:household-supplies": "home-and-kitchen/cleaning-and-household",
    "en:household-cleaning-supplies": "home-and-kitchen/cleaning-and-household",
    "en:household-cleaning-products": "home-and-kitchen/cleaning-and-household",
    "en:detergents": "home-and-kitchen/cleaning-and-household/laundry-detergents",
    "en:liquid-detergent": "home-and-kitchen/cleaning-and-household/laundry-detergents",
    "en:laundry-detergent": "home-and-kitchen/cleaning-and-household/laundry-detergents",
    "en:laundry-supplies": "home-and-kitchen/cleaning-and-household/laundry-detergents",
    "en:home-fragrances": "home-and-kitchen/cleaning-and-household/air-fresheners",
    "en:kitchen-appliances": "home-and-kitchen/kitchen-appliances",
    "en:kitchen-dining": "home-and-kitchen/kitchenware",
    "en:decor": "home-and-kitchen/home-decor-and-lighting",
    "en:office-supplies": "stationery/office-supplies",
    "en:general-office-supplies": "stationery/office-supplies",
    "en:office-instruments": "stationery/office-supplies",
    "en:pens": "stationery/writing-instruments/pens",
    "en:pens-pencils": "stationery/writing-instruments",
    "en:writing-drawing-instruments": "stationery/writing-instruments",
    "en:notebooks-notepads": "stationery/paper-products/notebooks",
    "en:paper-products": "stationery/paper-products",
    "en:stationery": "stationery",
    "en:stationary": "stationery",
    "en:clothing": "apparel",
    "en:apparel-accessories": "apparel/fashion-accessories",
    "en:books": "books",
    "en:printed-publications": "books",
    "en:published-products": "books",
    "en:printed-media": "books",

    /* ---------------------------------------------------------------- pets */
    "en:pet-food": "pet-supplies/pet-food",
    "en:dry-pet-food": "pet-supplies/pet-food",
    "en:dog-and-cat-food": "pet-supplies/pet-food",
    "en:dog-food": "pet-supplies/pet-food/dog-food",
    "en:dry-dog-food": "pet-supplies/pet-food/dog-food",
    "en:cat-food": "pet-supplies/pet-food/cat-food",
    "en:dry-cat-food": "pet-supplies/pet-food/cat-food",
    "en:fish-food": "pet-supplies/pet-food/fish-and-bird-food",
  },

  /**
   * Name keywords, used only when no tag mapped. Deliberately conservative - a keyword
   * that misfiles ("milk" in "milk chocolate", "chips" in "choco chips") is worse than none.
   */
  keywords: [
    [/\b(shampoo)\b/, "personal-care/hair-care/shampoo"],
    [/\b(conditioner)\b/, "personal-care/hair-care/conditioner"],
    [/\b(toothpaste|tooth paste|dentifrice)\b/, "personal-care/oral-care/toothpaste"],
    [/\b(toothbrush)\b/, "personal-care/oral-care/toothbrushes"],
    [/\b(body wash|shower gel)\b/, "personal-care/bath-and-body/body-wash"],
    [/\b(body lotion)\b/, "personal-care/bath-and-body/body-lotions"],
    [/\b(soap)\b/, "personal-care/bath-and-body/soaps"],
    [/\b(hand ?wash|sanitizer|sanitiser)\b/, "personal-care/hand-wash-and-sanitisers"],
    [/\b(deodorant|roll on)\b/, "personal-care/deodorants"],
    [/\b(perfume|eau de toilette|eau de parfum|body spray)\b/, "beauty/fragrances/perfumes"],
    [/\b(face ?wash)\b/, "beauty/skincare/face-wash-and-cleansers"],
    [/\b(sunscreen|sun screen)\b/, "beauty/skincare/sunscreen"],
    [/\b(detergent)\b/, "home-and-kitchen/cleaning-and-household/laundry-detergents"],
    [/\b(basmati)\b/, "grocery/staples/rice/basmati-rice"],
    [/\b(biscuits?|cookies)\b/, "food/biscuits-and-cookies"],
    [/\b(noodles)\b/, "food/instant-and-ready-to-eat/noodles"],
    [/\b(pasta|macaroni)\b/, "food/instant-and-ready-to-eat/pasta-and-macaroni"],
    [/\b(potato chips|potato crisps)\b/, "food/snacks/chips-and-crisps"],
    [/\b(green tea|black tea|tea bags?)\b/, "beverages/tea"],
    [/\b(plush|teddy)\b/, "toys/soft-toys"],
    [/\b(puzzle)\b/, "toys/games-and-puzzles/puzzles"],
    [/\b(notebook)\b/, "stationery/paper-products/notebooks"],
    [/\b(ball pen|gel pen|fountain pen)\b/, "stationery/writing-instruments/pens"],
    [/\b(usb cable|type c cable|charger)\b/, "electronics/power-and-accessories"],
    [/\b(headphones?|earphones?|earbuds?)\b/, "electronics/tvs-and-audio/headphones-and-earphones"],
    [/\b(smartphone|mobile phone)\b/, "electronics/mobiles/smartphones"],
    [/\b(dog food)\b/, "pet-supplies/pet-food/dog-food"],
    [/\b(cat food)\b/, "pet-supplies/pet-food/cat-food"],
  ],
};
